osstotalsoft/generator-webapp-rocket

- README.md
- generators/app/templates/infrastructure/Dockerfile
- generators/app/templates/infrastructure/package.json
- package.json
> bump node version specs

- generators/app/templates/infrastructure/src/components/routing/PrivateRoute.js
Added emptyArray import inside withRights condition
> added emptyArray import in withRights condition

- README.md
- generators/app/templates/infrastructure/Dockerfile
- generators/app/templates/infrastructure/helm/frontend/templates/deployment.yaml
- generators/app/templates/infrastructure/helm/frontend/values.yaml
For a better security, a non root user is created once the project is generated under which the application will run in container.
> update dockerfile with non root user

- generators/app/templates/infrastructure/src/providers/AuthenticationProvider.js
Automatically redirect to login page after logging out from a different tab
> Fix redirect when logging out from different tab

- generators/app/templates/infrastructure/src/index.js
Add missing SuperResponsiveTableStyle.css import in index.js application entry-point
> Add missing SuperResponsiveTableStyle.css import

- generators/app/templates/infrastructure/src/apollo/AuthApolloProvider.js
- generators/app/templates/infrastructure/src/apollo/client.js
- removed apollo client dependency of oidcUser
- got the token from UserManager from @axa-fr/react-oidc-core inside the links
> made apollo client "singleton"

- .eslintrc.json
- .vscode/launch.json
- README.md
- __tests__/app.js
- __tests__/installers.js
- generators/app/index.js
- package-lock.json
- package.json
- upgrade generator packages
- install latest version of yeoman
- cleanup tests
> upgrade yeoman and cleanup tests

- generators/app/templates/infrastructure/src/apollo/client.js
- generators/app/templates/infrastructure/src/components/routing/CustomRoute.js
FIX - Bring back PrivateRoute full functionality
> Add missing PrivateRoute functionality (rights)

- generators/app/templates/infrastructure/src/assets/css/index.css
- generators/app/templates/infrastructure/src/components/menu/UserMenuItem.js
> Add browser scrollbar styles

- generators/app/templates/infrastructure/src/assets/jss/components/appStyle.js
This reverts commit 04ac5435656d5743c228aec0e45d19549cfe2cec.
> Revert "Fix app content background minHeight "

- generators/app/templates/infrastructure/src/hooks/apolloLocalStorage.js
investigated the warning and fixed the object reference from issue #27
> Feature fix Apollo local storage hook

- generators/app/templates/infrastructure/public/static/locales/en/translations.json
- generators/app/templates/infrastructure/public/static/locales/ro/translations.json
- generators/app/templates/infrastructure/src/assets/jss/components/menuStyle.js
- generators/app/templates/infrastructure/src/components/menu/CollapsibleMenuItem.js
- generators/app/templates/infrastructure/src/components/menu/Menu.js
- generators/app/templates/infrastructure/src/components/menu/MenuItem.js
- generators/app/templates/infrastructure/src/constants/menuConfig.js
- generators/app/templates/infrastructure/src/features/settings/PrivacySettings.js
- generators/app/templates/infrastructure/src/features/settings/SecuritySettings.js
- generators/app/templates/infrastructure/src/routes/AppRoutes.js
Add collapsible sub-menu to sidebar
> Add collapsible sub-menu to sidebar

- generators/app/templates/infrastructure/src/assets/jss/components/menuStyle.js
- generators/app/templates/infrastructure/src/assets/jss/components/tenantSelectorStyle.js
> Fix naming typos in assets files

- generators/app/templates/infrastructure/src/assets/css/index.css
> Downsize scrollbar width

- generators/app/templates/infrastructure/src/assets/jss/components/menuStyle.js
> fix alignment between icon and text in ListItem

- generators/app/templates/infrastructure/src/assets/jss/components/menuStyle.js
> Add ellipsis on menu items

- generators/app/templates/infrastructure/package.json
due to https://github.com/AxaGuilDEv/react-oidc/issues/665
> Downgrade @axa-fr/react-oidc-context to v 3.1.6 

- generators/app/templates/infrastructure/src/apollo/client.js
Issue: Some events coming from backend are not caught in the UI when they're being emitted at the same time the token becomes expired.
Solution: Check web socket connection with ping, and if the access token has changed, close the current connection, which will reinitialize it with the new token.
> Check access token and recreate web socket connection if token changed

- generators/app/constants.js
- generators/app/index.js
- generators/app/questions.js
- generators/app/templates/infrastructure/package.json
- generators/utils.js
User configurations, decided when generating/upgrading a project, are saved in .yo.rc.json file. When regenerating over an existing project with pre-saved configurations, the user can choose to use them instead of answering all the questions again.
> Save generator options in local project storage

- generators/app/templates/infrastructure/src/components/menu/user/UserMenuStyle.js
Add margin top style for user arrow
> small fix user arrow drop

- generators/app/templates/infrastructure/src/assets/css/index.css
- generators/app/templates/infrastructure/src/utils/propertyChangeAdapters/index.js
- Remove Toast close button from index.css. Now, the style is in the component style
- Update onPropertyChange. Is receiving now directly the value, not the event
> delete close button style toast + change onPropertyChange

- __tests__/installers.js
- generators/app/index.js
Fixed deleting files after generating
> fix tests and delete files and folders

- generators/app/index.js
Undo delete implementation for now
> undo delete implementation

- generators/app/templates/infrastructure/src/components/menu/user/UserMenuStyle.js
Add background property if the value contains gradient
> fix background gradient

- __tests__/installers.js
- generators/app/constants.js
- generators/app/templates/infrastructure/Dockerfile
- generators/app/templates/infrastructure/package.json
- package-lock.json
- package.json
- Upgrade NodeJS to v18.x and npm to v9.x
> Node Upgrade

- generators/app/templates/infrastructure/helm/frontend/templates/ingress.yaml
- generators/app/templates/infrastructure/helm/frontend/values.yaml
Add ingress file configuration in helm files
> add ingress file

- generators/app/templates/infrastructure/src/apollo/AuthApolloProvider.js
Fix import setAccessToken function
> fix import oidc token

- generators/app/templates/infrastructure/src/apollo/client.js
- generators/app/templates/infrastructure/src/components/menu/user/UserMenu.js
- generators/app/templates/infrastructure/src/utils/auth/authConfig.js
> fix logout call

- generators/app/templates/infrastructure/package.json
replace uuidv4 library with uuid
> replace uuidv4 library with uuid

- generators/app/templates/infrastructure/package.json
- generators/app/templates/infrastructure/src/apollo/AuthApolloProvider.js
- generators/app/templates/infrastructure/src/apollo/client.js
- generators/app/templates/infrastructure/src/components/menu/Menu.js
- generators/app/templates/infrastructure/src/components/menu/user/UserMenu.js
- generators/app/templates/infrastructure/src/components/routing/CustomRoute.js
- generators/app/templates/infrastructure/src/hooks/rights.js
- generators/app/templates/infrastructure/src/utils/simple-validations/validations.js
1. Merge `useUserData` and `useRights` hooks.
2. Replace `moment` with `date-fns`.
3. Small fixes in `apollo/client.js` and `apollo/AuthApolloProvider.js`
#30
> merge hooks

- generators/app/templates/infrastructure/src/components/layout/header/Header.js
- generators/app/templates/infrastructure/src/components/layout/header/MobileHeader.js
- generators/app/templates/infrastructure/src/components/layout/header/WebHeader.js
- generators/app/templates/infrastructure/src/components/layout/sidebar/MobileSidebar.js
- generators/app/templates/infrastructure/src/components/layout/sidebar/Sidebar.js
- generators/app/templates/infrastructure/src/components/layout/sidebar/SidebarWrapper.js
- generators/app/templates/infrastructure/src/components/layout/sidebar/WebSidebar.js
- generators/app/templates/infrastructure/src/utils/constants.js
Fixed the duplicate header problem and removed the deprecated Hidden component
> Removed deprecated Hidden from Sidebar and Header

- generators/app/templates/infrastructure/package.json
- generators/app/templates/infrastructure/public/OidcTrustedDomains.js
- generators/app/templates/infrastructure/setOidcDomains.js
- generators/app/templates/infrastructure/src/assets/css/index.css
- generators/app/templates/infrastructure/src/components/App.js
- generators/app/templates/infrastructure/src/components/AppStyle.js
- generators/app/templates/infrastructure/src/components/layout/footer/Footer.js
- generators/app/templates/infrastructure/src/components/layout/footer/FooterStyle.js
- generators/app/templates/infrastructure/src/components/layout/header/Header.js
- generators/app/templates/infrastructure/src/components/layout/header/HeaderStyle.js
- generators/app/templates/infrastructure/src/components/layout/header/MobileHeader.js
- generators/app/templates/infrastructure/src/components/layout/header/WebHeader.js
- generators/app/templates/infrastructure/src/components/layout/sidebar/SidebarStyle.js
- generators/app/templates/infrastructure/src/components/layout/sidebar/SidebarWrapper.js
- generators/app/templates/infrastructure/src/components/menu/MenuStyle.js
- generators/app/templates/infrastructure/src/components/menu/tenant/TenantSelector.js
- generators/app/templates/infrastructure/src/features/dashboard/Dashboard.js
- generators/app/templates/infrastructure/src/features/settings/PrivacySettings.js
- generators/app/templates/infrastructure/src/features/settings/SecuritySettings.js
- generators/app/templates/infrastructure/src/index.js
- generators/app/templates/infrastructure/src/routes/config.js
Refactor header and footer components
Update material-ui libraries
Fix error when authentication provider is not configured
> Refactor header and footer

- generators/app/templates/infrastructure/.dockerignore
> add dockerignore
